"""empty message

Revision ID: a65fa30520d5
Revises: 9f543ca62d40
Create Date: 2020-03-06 03:24:08.763789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65fa30520d5'
down_revision = '9f543ca62d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('time_start', sa.Integer(), nullable=True),
    sa.Column('time_end', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_comment', sa.String(length=255), nullable=True),
    sa.Column('manager_comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_time_end'), 'meeting', ['time_end'], unique=False)
    op.create_index(op.f('ix_meeting_time_start'), 'meeting', ['time_start'], unique=False)
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_meeting_time_start'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_time_end'), table_name='meeting')
    op.drop_table('meeting')
    # ### end Alembic commands ###
